@echo off
TITLE=Roots and Revoked Certificates Updater
MODE CON COLS=56 LINES=22
COLOR 1F

SET "LASTAUTH=20180718"
SET "LASTDEL=20180706"
SET "LASTROOT=20180706"
SET "LASTUPD=20180821"
SET "LASTDISALLOWED=20180427"

SET "SLEEPTIMER=2"
SET "ERRORLOOPS=30"

SET "LogFileEnable=0"
SET "EndTimer=0"

SET "DLURL=http://wsus.ds.download.windowsupdate.com/msdownload/update/v3/static/trustedr/en"
SET "DLURLDELTA1=http://ds.download.windowsupdate.com/msdownload/update/v3/static/trustedr/en"
SET "DLURLDELTA2=0"
SET "DLURLDELTA3=0"
SET "DLURLDELTA4=0"
SET "DLURLDELTA5=0"

SET "CertUpdRegURL=0"

SET "WEBSPIDER=1"

SET "DLFILE1=authroots.sst"
SET "DLFILE2=delroots.sst"
SET "DLFILE3=roots.sst"
SET "DLFILE4=updroots.sst"
SET "DLFILE5=disallowedcert.sst"

SET "DLFILES=5"

SET "DLDATEREGNAME1=AUTH"
SET "DLDATEREGNAME2=DEL"
SET "DLDATEREGNAME3=ROOT"
SET "DLDATEREGNAME4=UPD"
SET "DLDATEREGNAME5=DISALLOWED"

SET "DATEREGNAMEEND=DATE"

SET "DLFILENB=1"
SET "LOOPDLFILES=1"
SET "LOOPCERTDL=1"

SET "MODAUTHDATE=00000000"
SET "MODDELDATE=00000000"
SET "MODROOTDATE=00000000"
SET "MODUPDDATE=00000000"
SET "MODDISALLOWEDDATE=00000000"

SET "LOOPCOUNTER=1"
SET "WAITTIME=%SLEEPTIMER%"
SET "DLERROR=0"
SET "LOOPDECRYPTINT=0"
SET "LOKALUPD=0"
SET "DELTAFORMULA=LEQ"

(REG ADD "HKLM\Software\Cert_Updater" /f /v "Version" /t REG_SZ /d "1.6") >NUL 2>&1

((FOR /F "tokens=2* delims=	 " %%a IN ('REG QUERY "HKLM\Software\Cert_Updater" /v "%DLDATEREGNAME1%%DATEREGNAMEEND%"') DO SET "LASTCERTDATEDAT1INTCH=%%a"&&SET "LASTCERTDATEDAT1INT=%%b")&&(FOR /F "tokens=2* delims=	 " %%a IN ('REG QUERY "HKLM\Software\Cert_Updater" /v "%DLDATEREGNAME2%%DATEREGNAMEEND%"') DO SET "LASTCERTDATEDAT2INTCH=%%a"&&SET "LASTCERTDATEDAT2INT=%%b")&&(FOR /F "tokens=2* delims=	 " %%a IN ('REG QUERY "HKLM\Software\Cert_Updater" /v "%DLDATEREGNAME3%%DATEREGNAMEEND%"') DO SET "LASTCERTDATEDAT3INTCH=%%a"&&SET "LASTCERTDATEDAT3INT=%%b")&&(FOR /F "tokens=2* delims=	 " %%a IN ('REG QUERY "HKLM\Software\Cert_Updater" /v "%DLDATEREGNAME4%%DATEREGNAMEEND%"') DO SET "LASTCERTDATEDAT4INTCH=%%a"&&SET "LASTCERTDATEDAT4INT=%%b")&&(FOR /F "tokens=2* delims=	 " %%a IN ('REG QUERY "HKLM\Software\Cert_Updater" /v "%DLDATEREGNAME5%%DATEREGNAMEEND%"') DO SET "LASTCERTDATEDAT5INTCH=%%a"&&SET "LASTCERTDATEDAT5INT=%%b")&&(FOR /F "tokens=2* delims=	 " %%a IN ('REG QUERY "HKLM\Software\Cert_Updater" /v "SST_Download_URL"') DO SET "CertsDLURLREGCH=%%a"&&SET "CertsDLURLREG=%%b")&&(FOR /F "tokens=2* delims=	 " %%a IN ('REG QUERY "HKLM\Software\Cert_Updater" /v "SST_Download_URL_D1"') DO SET "CertsDLURLD1REGCH=%%a"&&SET "CertsDLURLD1REG=%%b")&&(FOR /F "tokens=2* delims=	 " %%a IN ('REG QUERY "HKLM\Software\Cert_Updater" /v "SST_Download_URL_D2"') DO SET "CertsDLURLD2REGCH=%%a"&&SET "CertsDLURLD2REG=%%b")&&(FOR /F "tokens=2* delims=	 " %%a IN ('REG QUERY "HKLM\Software\Cert_Updater" /v "SST_Download_URL_D3"') DO SET "CertsDLURLD3REGCH=%%a"&&SET "CertsDLURLD3REG=%%b")&&(FOR /F "tokens=2* delims=	 " %%a IN ('REG QUERY "HKLM\Software\Cert_Updater" /v "SST_Download_URL_D4"') DO SET "CertsDLURLD4REGCH=%%a"&&SET "CertsDLURLD4REG=%%b")&&(FOR /F "tokens=2* delims=	 " %%a IN ('REG QUERY "HKLM\Software\Cert_Updater" /v "SST_Download_URL_D5"') DO SET "CertsDLURLD5REGCH=%%a"&&SET "CertsDLURLD5REG=%%b")&&(FOR /F "tokens=2* delims=	 " %%a IN ('REG QUERY "HKLM\Software\Cert_Updater" /v "max_number_of_download_attempts"') DO SET "ERRORLOOPSREGCH=%%a"&&SET "ERRORLOOPSREG=%%b")&&(FOR /F "tokens=2* delims=	 " %%a IN ('REG QUERY "HKLM\Software\Cert_Updater" /v "file_for_settings_URL"') DO SET "CertUpdRegURLREGCH=%%a"&&SET "CertUpdRegURLREG=%%b")&&(FOR /F "tokens=2* delims=	 " %%a IN ('REG QUERY "HKLM\Software\Cert_Updater" /v "log_file_enable"') DO SET "LogFileEnableREGCH=%%a"&&SET "LogFileEnableREG=%%b")&&(FOR /F "tokens=2* delims=	 " %%a IN ('REG QUERY "HKLM\Software\Cert_Updater" /v "end_timer"') DO SET "EndTimerREGCH=%%a"&&SET "EndTimerREG=%%b")&&(FOR /F "tokens=2* delims=	 " %%a IN ('REG QUERY "HKLM\Software\Cert_Updater" /v "webspider_to_compare"') DO SET "WEBSPIDERREGCH=%%a"&&SET "WEBSPIDERREG=%%b")) >NUL 2>&1

(IF "%LASTCERTDATEDAT1INTCH%" == "REG_SZ" (SET "LASTAUTH=%LASTCERTDATEDAT1INT%") ELSE (REG ADD "HKLM\Software\Cert_Updater" /f /v "%DLDATEREGNAME1%%DATEREGNAMEEND%" /t REG_SZ /d %LASTAUTH%)) >NUL 2>&1
(IF "%LASTCERTDATEDAT2INTCH%" == "REG_SZ" (SET "LASTDEL=%LASTCERTDATEDAT2INT%") ELSE (REG ADD "HKLM\Software\Cert_Updater" /f /v "%DLDATEREGNAME2%%DATEREGNAMEEND%" /t REG_SZ /d %LASTDEL%)) >NUL 2>&1
(IF "%LASTCERTDATEDAT3INTCH%" == "REG_SZ" (SET "LASTROOT=%LASTCERTDATEDAT3INT%") ELSE (REG ADD "HKLM\Software\Cert_Updater" /f /v "%DLDATEREGNAME3%%DATEREGNAMEEND%" /t REG_SZ /d %LASTROOT%)) >NUL 2>&1
(IF "%LASTCERTDATEDAT4INTCH%" == "REG_SZ" (SET "LASTUPD=%LASTCERTDATEDAT4INT%") ELSE (REG ADD "HKLM\Software\Cert_Updater" /f /v "%DLDATEREGNAME4%%DATEREGNAMEEND%" /t REG_SZ /d %LASTUPD%)) >NUL 2>&1
(IF "%LASTCERTDATEDAT5INTCH%" == "REG_SZ" (SET "LASTDISALLOWED=%LASTCERTDATEDAT5INT%") ELSE (REG ADD "HKLM\Software\Cert_Updater" /f /v "%DLDATEREGNAME5%%DATEREGNAMEEND%" /t REG_SZ /d %LASTDISALLOWED%)) >NUL 2>&1
(IF "%CertsDLURLREGCH%" == "REG_SZ" (SET "DLURL=%CertsDLURLREG%") ELSE (REG ADD "HKLM\Software\Cert_Updater" /f /v "SST_Download_URL" /t REG_SZ /d %DLURL%)) >NUL 2>&1
(IF "%CertsDLURLD1REGCH%" == "REG_SZ" (SET "DLURLDELTA1=%CertsDLURLD1REG%") ELSE (REG ADD "HKLM\Software\Cert_Updater" /f /v "SST_Download_URL_D1" /t REG_SZ /d %DLURLDELTA1%)) >NUL 2>&1
(IF "%CertsDLURLD2REGCH%" == "REG_SZ" (SET "DLURLDELTA2=%CertsDLURLD2REG%") ELSE (REG ADD "HKLM\Software\Cert_Updater" /f /v "SST_Download_URL_D2" /t REG_SZ /d %DLURLDELTA2%)) >NUL 2>&1
(IF "%CertsDLURLD3REGCH%" == "REG_SZ" (SET "DLURLDELTA3=%CertsDLURLD3REG%") ELSE (REG ADD "HKLM\Software\Cert_Updater" /f /v "SST_Download_URL_D3" /t REG_SZ /d %DLURLDELTA3%)) >NUL 2>&1
(IF "%CertsDLURLD4REGCH%" == "REG_SZ" (SET "DLURLDELTA4=%CertsDLURLD4REG%") ELSE (REG ADD "HKLM\Software\Cert_Updater" /f /v "SST_Download_URL_D4" /t REG_SZ /d %DLURLDELTA4%)) >NUL 2>&1
(IF "%CertsDLURLD5REGCH%" == "REG_SZ" (SET "DLURLDELTA5=%CertsDLURLD5REG%") ELSE (REG ADD "HKLM\Software\Cert_Updater" /f /v "SST_Download_URL_D5" /t REG_SZ /d %DLURLDELTA5%)) >NUL 2>&1
(IF "%ERRORLOOPSREGCH%" == "REG_SZ" (SET "ERRORLOOPS=%ERRORLOOPSREG%") ELSE (REG ADD "HKLM\Software\Cert_Updater" /f /v "max_number_of_download_attempts" /t REG_SZ /d %ERRORLOOPS%)) >NUL 2>&1
(IF "%CertUpdRegURLREGCH%" == "REG_SZ" (SET "CertUpdRegURL=%CertUpdRegURLREG%") ELSE (REG ADD "HKLM\Software\Cert_Updater" /f /v "file_for_settings_URL" /t REG_SZ /d %CertUpdRegURL%)) >NUL 2>&1
(IF "%LogFileEnableREGCH%" == "REG_SZ" (SET "LogFileEnable=%LogFileEnableREG%") ELSE (REG ADD "HKLM\Software\Cert_Updater" /f /v "log_file_enable" /t REG_SZ /d "%LogFileEnable%")) >NUL 2>&1
(IF "%EndTimerREGCH%" == "REG_SZ" (SET "EndTimer=%EndTimerREG%") ELSE (REG ADD "HKLM\Software\Cert_Updater" /f /v "end_timer" /t REG_SZ /d "%EndTimer%")) >NUL 2>&1
(IF "%WEBSPIDERREGCH%" == "REG_SZ" (SET "WEBSPIDER=%WEBSPIDERREG%") ELSE (REG ADD "HKLM\Software\Cert_Updater" /f /v "webspider_to_compare" /t REG_SZ /d "%WEBSPIDER%")) >NUL 2>&1

rem (FOR /F "tokens=2* delims=	 " %%a IN ('REG QUERY "HKLM\Software\Cert_Updater" /v "end_timer"') DO SET "EndTimerREGCH=%%a"&&SET "EndTimerREG=%%b") >NUL 2>&1
rem (IF "%EndTimerREGCH%" == "REG_SZ" (SET "EndTimer=%EndTimerREG%") ELSE (REG ADD "HKLM\Software\Cert_Updater" /f /v "end_timer" /t REG_SZ /d "%EndTimer%")) >NUL 2>&1

(IF "%DLURL%" == "0" SET "DELTAFORMULA=LSS") >NUL 2>&1
(IF "%DLURLDELTA1%" == "0" SET "DLURLDELTA1=") >NUL 2>&1
(IF "%DLURLDELTA2%" == "0" SET "DLURLDELTA2=") >NUL 2>&1
(IF "%DLURLDELTA3%" == "0" SET "DLURLDELTA3=") >NUL 2>&1
(IF "%DLURLDELTA4%" == "0" SET "DLURLDELTA4=") >NUL 2>&1
(IF "%DLURLDELTA5%" == "0" SET "DLURLDELTA5=") >NUL 2>&1

(IF NOT "%1" == "" IF NOT "%1" == "X" SET "LogFileEnable=%1") >NUL 2>&1
(IF NOT "%2" == "" IF NOT "%2" == "X" SET "EndTimer=%2") >NUL 2>&1
(IF NOT "%3" == "" IF NOT "%3" == "X" SET "ERRORLOOPS=%3") >NUL 2>&1
(IF NOT "%4" == "" IF NOT "%4" == "X" SET "WEBSPIDER=%4") >NUL 2>&1

(IF "%WEBSPIDER%" == "1" (SET "DELTASPIDER= --spider") ELSE (SET "DELTASPIDER=")) >NUL 2>&1

rem (MD "CERTDLTMP") >NUL 2>&1
rem (MD "CERTDLTMPD1") >NUL 2>&1
rem (MD "CERTDLTMPD2") >NUL 2>&1
rem (MD "CERTDLTMPD3") >NUL 2>&1
rem (MD "CERTDLTMPD4") >NUL 2>&1
rem (MD "CERTDLTMPD5") >NUL 2>&1


SET "PASSCODE1=c6TydN4h2A1k0iWquoB3px8JU7RclvQ4Z0LSVrw9MYFe3o5gOpvCz6tCU7lvQ4Z0LSqVrc6T4h2a1kwmFe3I5gpQ4Zn0LSVrYw9MFe3D5GpCvCOz6tU7lv"

SET "CERTUPDPATH=%PathInst%"

IF NOT EXIST "%CERTUPDPATH%\CertUpd.jpg" GOTO NEXTINT1 >NUL 2>&1
(SET "LOKALUPD=1") >NUL 2>&1
(FOR %%f in ("%CERTUPDPATH%\CertUpd.jpg") DO SET "FILE=%%~zf") >NUL 2>&1
(COPY "%CERTUPDPATH%\CertUpd.jpg" "CertUpd.7z") >NUL 2>&1
(SET "LOOPDECRYPTINT=1") >NUL 2>&1
GOTO NEXTINTWORK
:NEXTINT1

IF NOT EXIST "%CERTUPDPATH%\Cert_Updater.txt" GOTO NEXTINT2 >NUL 2>&1
HTTPDL.exe -q -t 3 -T 3 -c -i "%CERTUPDPATH%\Cert_Updater.txt"
IF NOT EXIST "CertUpd.jpg" GOTO NEXTINT2 >NUL 2>&1
(SET "LOOPDECRYPTINT=1") >NUL 2>&1

:LOOPDECRYPT

(FOR %%f in ("CertUpd.jpg") DO SET "FILE=%%~zf") >NUL 2>&1
REN CertUpd.jpg CertUpd.7z >NUL 2>&1

:NEXTINTWORK

(SET FILEX=%FILE:~-1%) >NUL 2>&1
(IF "%FILEX%" == "0" SET FILEX=%FILE:~-2,-1%) >NUL 2>&1
(IF "%FILEX%" == "0" SET FILEX=%FILE:~-3,-2%) >NUL 2>&1
(IF "%FILEX%" == "0" SET FILEX=%FILE:~-4,-3%) >NUL 2>&1
(SET FILEY=%FILEX%) >NUL 2>&1
(IF "%FILEX%" == "0" SET FILEY=1) >NUL 2>&1

(SET FILE2=%FILE:~-1%) >NUL 2>&1
(SET FILE3=%FILE:~-2,-1%) >NUL 2>&1
(SET FILE4=%FILE:~-3,-2%) >NUL 2>&1
(SET FILE5=%FILE:~-4,-3%) >NUL 2>&1
(SET FILE6=%FILE:~-5,-4%) >NUL 2>&1
(SET FILE7=%FILE:~-6,-5%) >NUL 2>&1
(SET FILE8=%FILE:~-7,-6%) >NUL 2>&1
(SET FILE9=%FILE:~-8,-7%) >NUL 2>&1
(SET FILE10=%FILE:~-9,-8%) >NUL 2>&1
(IF "%FILE4%" == "" SET FILE4=1) >NUL 2>&1
(IF "%FILE5%" == "" SET FILE5=1) >NUL 2>&1
(IF "%FILE6%" == "" SET FILE6=1) >NUL 2>&1
(IF "%FILE7%" == "" SET FILE7=1) >NUL 2>&1
(IF "%FILE8%" == "" SET FILE8=1) >NUL 2>&1
(IF "%FILE9%" == "" SET FILE9=1) >NUL 2>&1
(IF "%FILE10%" == "" SET FILE10=1) >NUL 2>&1
(IF "%FILE2%" == "0" SET FILE2=1) >NUL 2>&1
(IF "%FILE3%" == "0" SET FILE3=1) >NUL 2>&1
(IF "%FILE4%" == "0" SET FILE4=1) >NUL 2>&1
(IF "%FILE5%" == "0" SET FILE5=1) >NUL 2>&1
(IF "%FILE6%" == "0" SET FILE6=1) >NUL 2>&1
(IF "%FILE7%" == "0" SET FILE7=1) >NUL 2>&1
(IF "%FILE8%" == "0" SET FILE8=1) >NUL 2>&1
(IF "%FILE9%" == "0" SET FILE9=1) >NUL 2>&1
(IF "%FILE10%" == "0" SET FILE10=1) >NUL 2>&1

(SET /a FILEZ=%FILE%*%FILEY%+%FILE%) >NUL 2>&1
(SET /a FILE12=%FILE2%*%FILE3%*%FILE4%*%FILE5%*%FILE6%*%FILE7%*%FILE8%*%FILE9%*%FILE10%*%FILEY%+%FILE%) >NUL 2>&1
(SET /a FILEB=%FILEZ%+%FILE12%) >NUL 2>&1
(SET /a FILEC=%FILEZ%+%FILE12%+%FILE%) >NUL 2>&1

(SET /a LENGTHVAR=0) >NUL 2>&1
(SET "T=%FILE%") >NUL 2>&1
:LOOP1
(IF NOT DEFINED T GOTO EXIT1) >NUL 2>&1
(SET /a LENGTHVAR+=1) >NUL 2>&1
(SET "T=%T:~,-1%") >NUL 2>&1
GOTO LOOP1
:EXIT1

(SET /a LENGTHVAR=%LENGTHVAR%+%FILEY%) >NUL 2>&1
(SET /a LENGTHVAR2=%LENGTHVAR%+%FILEY%) >NUL 2>&1
(SET /a FILEC=%FILEC%*%LENGTHVAR2%) >NUL 2>&1

(CALL SET "PASSCODE2=%%PASSCODE1:~%FILEX%,-%LENGTHVAR%%%") >NUL 2>&1
(CALL SET "PASSCODE3=%%PASSCODE2:~,%LENGTHVAR2%%%") >NUL 2>&1
(CALL SET "PASSCODE4=%%PASSCODE2:~%LENGTHVAR2%%%") >NUL 2>&1

(7za920\7za.exe x -aoa CertUpd.7z -p%FILEZ%%PASSCODE3%%FILEB%%PASSCODE4%%FILEC%) >NUL 2>&1
DEL CertUpd.7z >NUL 2>&1

(IF EXIST hZt4wU83.zip GOTO NOERROR) >NUL 2>&1
CLS
ECHO.
ECHO  Error, no suitable data available!
ECHO.
GOTO NEXT4
:NOERROR
CLS
ECHO.
ECHO  Please wait, data will be generated ....
ECHO.

(FOR %%f in ("hZt4wU83.zip") DO SET "FILEA=%%~zf") >NUL 2>&1

(SET FILEX2=%FILEA:~-2,-1%) >NUL 2>&1
(IF "%FILEX2%" == "0" SET FILEX2=%FILEA:~-3,-2%) >NUL 2>&1
(IF "%FILEX2%" == "0" SET FILEX2=%FILEA:~-4,-3%) >NUL 2>&1
(SET FILEY2=%FILEX2%) >NUL 2>&1
(IF "%FILEX2%" == "0" SET FILEY2=10) >NUL 2>&1
(SET /a FILEX3=%FILEX%+%FILEX2%) >NUL 2>&1
(SET /a FILEZ2=%FILE%*%FILEY2%+%FILEA%) >NUL 2>&1
(SET /a FILEA=%LENGTHVAR%*%FILEA%) >NUL 2>&1
(SET /a LENGTHVAR3=%LENGTHVAR%+%FILEY+%FILEY2%) >NUL 2>&1

(7za920\7za.exe x -aoa hZt4wU83.zip -p%FILEZ2%%FILEA%%PASSCODE4%%FILEZ%%FILEC%%LENGTHVAR%%PASSCODE3%%FILE12%%FILEB%) >NUL 2>&1
(FOR /F "delims=:" %%f in ('TYPE x7g4Q1RuH') DO Set "INTDATA=%%f") >NUL 2>&1
DEL x7g4Q1RuH >NUL 2>&1

(CALL SET "INTDATA2=%%INTDATA:~%FILEX3%,-%LENGTHVAR%%%") >NUL 2>&1
(CALL SET "INTDATA3=%%INTDATA2:~,%LENGTHVAR3%%%") >NUL 2>&1
(CALL SET "INTDATA4=%%INTDATA2:~%LENGTHVAR3%%%") >NUL 2>&1

REN hZt4wU83.zip hZt4wU83.7z >NUL 2>&1
(7za920\7za.exe x -aoa hZt4wU83.7z -p%FILE12%%INTDATA4%%FILEA%%LENGTHVAR%%INTDATA3%%FILEZ2%) >NUL 2>&1
DEL hZt4wU83.7z >NUL 2>&1

IF NOT EXIST "CertUpd.set" GOTO NEXTINT2B >NUL 2>&1
((FOR /F %%a IN ('TYPE "CertUpd.set" ^|^ FIND "%DLDATEREGNAME1%%DATEREGNAMEEND%"') DO SET "%DLDATEREGNAME1%INT=%%a")&&(FOR /F %%a IN ('TYPE "CertUpd.set" ^|^ FIND "%DLDATEREGNAME2%%DATEREGNAMEEND%"') DO SET "%DLDATEREGNAME2%INT=%%a")&&(FOR /F %%a IN ('TYPE "CertUpd.set" ^|^ FIND "%DLDATEREGNAME3%%DATEREGNAMEEND%"') DO SET "%DLDATEREGNAME3%INT=%%a")&&(FOR /F %%a IN ('TYPE "CertUpd.set" ^|^ FIND "%DLDATEREGNAME4%%DATEREGNAMEEND%"') DO SET "%DLDATEREGNAME4%INT=%%a")&&(FOR /F %%a IN ('TYPE "CertUpd.set" ^|^ FIND "%DLDATEREGNAME5%%DATEREGNAMEEND%"') DO SET "%DLDATEREGNAME5%INT=%%a")) >NUL 2>&1
(CALL SET LASTDATESET1INT=%%%DLDATEREGNAME1%INT:~12,8%%&&CALL SET LASTDATESET2INT=%%%DLDATEREGNAME2%INT:~11,8%%&&CALL SET LASTDATESET3INT=%%%DLDATEREGNAME3%INT:~12,8%%&&CALL SET LASTDATESET4INT=%%%DLDATEREGNAME4%INT:~11,8%%&&CALL SET LASTDATESET5INT=%%%DLDATEREGNAME5%INT:~18,8%%) >NUL 2>&1
IF "%LOKALUPD%" == "1" GOTO LOKALUPDA >NUL 2>&1
(IF %LASTDATESET1INT% %DELTAFORMULA% %LASTAUTH% (SET DATESETINTDELTA1=1) ELSE (SET DATESETINTDELTA1=0)) >NUL 2>&1
(IF %LASTDATESET2INT% %DELTAFORMULA% %LASTDEL% (SET DATESETINTDELTA2=1) ELSE (SET DATESETINTDELTA2=0)) >NUL 2>&1
(IF %LASTDATESET3INT% %DELTAFORMULA% %LASTROOT% (SET DATESETINTDELTA3=1) ELSE (SET DATESETINTDELTA3=0)) >NUL 2>&1
(IF %LASTDATESET4INT% %DELTAFORMULA% %LASTUPD% (SET DATESETINTDELTA4=1) ELSE (SET DATESETINTDELTA4=0)) >NUL 2>&1
(IF %LASTDATESET5INT% %DELTAFORMULA% %LASTDISALLOWED% (SET DATESETINTDELTA5=1) ELSE (SET DATESETINTDELTA5=0)) >NUL 2>&1
(SET /A LASTDATESETINTDELTAJ1=%DATESETINTDELTA1%*%DATESETINTDELTA2%*%DATESETINTDELTA3%*%DATESETINTDELTA4%*%DATESETINTDELTA5%) >NUL 2>&1
IF "%LASTDATESETINTDELTAJ1%" == "1" GOTO NEXTINT2BB >NUL 2>&1
:LOKALUPDA
((SET "LASTAUTH=%LASTDATESET1INT%")&&(SET "LASTDEL=%LASTDATESET2INT%")&&(SET "LASTROOT=%LASTDATESET3INT%")&&(SET "LASTUPD=%LASTDATESET4INT%")&&(SET "LASTDISALLOWED=%LASTDATESET5INT%")) >NUL 2>&1
(COPY "CertUpd.set" "CertUpdSet.reg" /Y) >NUL 2>&1
(REG IMPORT "CertUpdSet.reg") >NUL 2>&1
GOTO NEXTINT2BBB

:NEXTINT2BB
(DEL "*.sst" /Q) >NUL 2>&1
:NEXTINT2BBB
(DEL "CertUpd.set" /Q) >NUL 2>&1
(DEL "*.reg" /Q) >NUL 2>&1
:NEXTINT2B

IF NOT EXIST "authroots.sst" GOTO NEXTINT2 >NUL 2>&1
IF NOT EXIST "delroots.sst" GOTO NEXTINT2 >NUL 2>&1
IF NOT EXIST "roots.sst" GOTO NEXTINT2 >NUL 2>&1
IF NOT EXIST "updroots.sst" GOTO NEXTINT2 >NUL 2>&1
IF NOT EXIST "disallowedcert.sst" GOTO NEXTINT2 >NUL 2>&1
((SET MODAUTHDATE=%LASTAUTH%)&&(SET MODDELDATE=%LASTDEL%)&&(SET MODDISALLOWEDDATE=%LASTDISALLOWED%)&&(SET MODROOTDATE=%LASTROOT%)&&(SET MODUPDDATE=%LASTUPD%)) >NUL 2>&1

GOTO NEXTINT3
:NEXTINT2
CLS

IF NOT EXIST "%CERTUPDPATH%\CertUpd.reg" GOTO NEXTINT2C >NUL 2>&1
(SET "LOKALUPD=1") >NUL 2>&1
(COPY "%CERTUPDPATH%\CertUpd.reg" "CertUpd.reg" /Y) >NUL 2>&1
(COPY "%CERTUPDPATH%\CertUpd.reg" "CertUpd.set" /Y) >NUL 2>&1
(REG IMPORT "CertUpd.reg") >NUL 2>&1
:NEXTINT2C

IF EXIST "CertUpd.reg" GOTO NEXTINT2D >NUL 2>&1
IF "%CertUpdRegURL%" == "0" GOTO NEXTINT2D >NUL 2>&1
IF "%LOOPDECRYPTINT%" == "0" HTTPDL.exe -q -t 3 -T 3 -c %CertUpdRegURL%
TITLE=Roots and Revoked Certificates Updater
:NEXTINT2D

IF "%LOOPDECRYPTINT%" == "1" GOTO LOOPDECRYPT2 >NUL 2>&1
IF EXIST "CertUpd.jpg" SET "LOOPDECRYPTINT=1" >NUL 2>&1
IF EXIST "CertUpd.jpg" GOTO LOOPDECRYPT >NUL 2>&1
:LOOPDECRYPT2
IF NOT EXIST "CertUpd.set" IF "%DELTAFORMULA%" == "LSS" GOTO NEXTINT3 >NUL 2>&1
IF NOT EXIST "CertUpd.set" GOTO LOOPDL >NUL 2>&1

((FOR /F %%a IN ('TYPE "CertUpd.set" ^|^ FIND "%DLDATEREGNAME1%%DATEREGNAMEEND%"') DO SET "%DLDATEREGNAME1%INT=%%a")&&(FOR /F %%a IN ('TYPE "CertUpd.set" ^|^ FIND "%DLDATEREGNAME2%%DATEREGNAMEEND%"') DO SET "%DLDATEREGNAME2%INT=%%a")&&(FOR /F %%a IN ('TYPE "CertUpd.set" ^|^ FIND "%DLDATEREGNAME3%%DATEREGNAMEEND%"') DO SET "%DLDATEREGNAME3%INT=%%a")&&(FOR /F %%a IN ('TYPE "CertUpd.set" ^|^ FIND "%DLDATEREGNAME4%%DATEREGNAMEEND%"') DO SET "%DLDATEREGNAME4%INT=%%a")&&(FOR /F %%a IN ('TYPE "CertUpd.set" ^|^ FIND "%DLDATEREGNAME5%%DATEREGNAMEEND%"') DO SET "%DLDATEREGNAME5%INT=%%a")) >NUL 2>&1
(CALL SET LASTDATESET1INT=%%%DLDATEREGNAME1%INT:~12,8%%&&CALL SET LASTDATESET2INT=%%%DLDATEREGNAME2%INT:~11,8%%&&CALL SET LASTDATESET3INT=%%%DLDATEREGNAME3%INT:~12,8%%&&CALL SET LASTDATESET4INT=%%%DLDATEREGNAME4%INT:~11,8%%&&CALL SET LASTDATESET5INT=%%%DLDATEREGNAME5%INT:~18,8%%) >NUL 2>&1
IF "%LOKALUPD%" == "1" GOTO LOKALUPDB >NUL 2>&1
(IF %LASTDATESET1INT% %DELTAFORMULA% %LASTAUTH% (SET DATESETINTDELTA1=1) ELSE (SET DATESETINTDELTA1=0)) >NUL 2>&1
(IF %LASTDATESET2INT% %DELTAFORMULA% %LASTDEL% (SET DATESETINTDELTA2=1) ELSE (SET DATESETINTDELTA2=0)) >NUL 2>&1
(IF %LASTDATESET3INT% %DELTAFORMULA% %LASTROOT% (SET DATESETINTDELTA3=1) ELSE (SET DATESETINTDELTA3=0)) >NUL 2>&1
(IF %LASTDATESET4INT% %DELTAFORMULA% %LASTUPD% (SET DATESETINTDELTA4=1) ELSE (SET DATESETINTDELTA4=0)) >NUL 2>&1
(IF %LASTDATESET5INT% %DELTAFORMULA% %LASTDISALLOWED% (SET DATESETINTDELTA5=1) ELSE (SET DATESETINTDELTA5=0)) >NUL 2>&1
(SET /A LASTDATESETINTDELTAJ2=%DATESETINTDELTA1%*%DATESETINTDELTA2%*%DATESETINTDELTA3%*%DATESETINTDELTA4%*%DATESETINTDELTA5%) >NUL 2>&1
IF "%LASTDATESETINTDELTAJ2%" == "1" GOTO NEXTINT2DD >NUL 2>&1
:LOKALUPDB
((SET "LASTAUTH=%LASTDATESET1INT%")&&(SET "LASTDEL=%LASTDATESET2INT%")&&(SET "LASTROOT=%LASTDATESET3INT%")&&(SET "LASTUPD=%LASTDATESET4INT%")&&(SET "LASTDISALLOWED=%LASTDATESET5INT%")) >NUL 2>&1
((REG ADD "HKLM\Software\Cert_Updater" /f /v "%DLDATEREGNAME1%%DATEREGNAMEEND%" /t REG_SZ /d %LASTAUTH%)&&(REG ADD "HKLM\Software\Cert_Updater" /f /v "%DLDATEREGNAME2%%DATEREGNAMEEND%" /t REG_SZ /d %LASTDEL%)&&(REG ADD "HKLM\Software\Cert_Updater" /f /v "%DLDATEREGNAME3%%DATEREGNAMEEND%" /t REG_SZ /d %LASTROOT%)&&(REG ADD "HKLM\Software\Cert_Updater" /f /v "%DLDATEREGNAME4%%DATEREGNAMEEND%" /t REG_SZ /d %LASTUPD%)&&(REG ADD "HKLM\Software\Cert_Updater" /f /v "%DLDATEREGNAME5%%DATEREGNAMEEND%" /t REG_SZ /d %LASTDISALLOWED%)) >NUL 2>&1
:NEXTINT2DD
(DEL "CertUpd.set" /Q) >NUL 2>&1
(DEL "*.reg" /Q) >NUL 2>&1

:LOOPDL
(CALL SET "HTTPDLFILE=%%DLFILE%DLFILENB%%%") >NUL 2>&1
(CALL SET "DLDATEREGNAME=%%DLDATEREGNAME%DLFILENB%%%") >NUL 2>&1
(CALL SET "LASTCERTDATE=%%LAST%DLDATEREGNAME%%%") >NUL 2>&1
((SET "MODCERTDATE=00000000")&&(SET "MODCERTDATED1=00000000")&&(SET "MODCERTDATED2=00000000")&&(SET "MODCERTDATED3=00000000")&&(SET "MODCERTDATED4=00000000")&&(SET "MODCERTDATED5=00000000")&&(SET "MODDATE=NA")&&(SET "MODDATED1=NA")&&(SET "MODDATED2=NA")&&(SET "MODDATED3=NA")&&(SET "MODDATED4=NA")&&(SET "MODDATED5=NA")) >NUL 2>&1
(IF "%DLERROR%" == "1" (SET WAITTIME=%SLEEPTIMER%)) >NUL 2>&1
((SET "DLERROR=0")&&(SET "DLURLD1=%DLURLDELTA1%")&&(SET "DLURLD2=%DLURLDELTA2%")&&(SET "DLURLD3=%DLURLDELTA3%")&&(SET "DLURLD4=%DLURLDELTA4%")&&(SET "DLURLD5=%DLURLDELTA5%")) >NUL 2>&1
HTTPDL.exe -t 3 -T 3 -c -S -o CERTDL.txt %DLURL%/%HTTPDLFILE%
SET "HTTPDLERROR=%ERRORLEVEL%"
(COPY "%HTTPDLFILE%" "CERTDLTMP\%HTTPDLFILE%" /Y) >NUL 2>&1
(IF EXIST "%HTTPDLFILE%" DEL "%HTTPDLFILE%") >NUL 2>&1
(IF "%HTTPDLERROR%" == "4" SET "DLERROR=1") >NUL 2>&1
IF "%DLURLD1%" == "" GOTO DLURLD1INT1 >NUL 2>&1
HTTPDL.exe -t 3 -T 3 -c -S%DELTASPIDER% -o CERTDLD1.txt %DLURLD1%/%HTTPDLFILE%
SET "HTTPDLERRORD1=%ERRORLEVEL%"
(IF "%WEBSPIDER%" == "0" (COPY "%HTTPDLFILE%" "CERTDLTMPD1\%HTTPDLFILE%" /Y)) >NUL 2>&1
(IF "%WEBSPIDER%" == "0" (IF EXIST "%HTTPDLFILE%" DEL "%HTTPDLFILE%")) >NUL 2>&1
(IF "%HTTPDLERRORD1%" == "4" SET "DLURLD1=") >NUL 2>&1
:DLURLD1INT1
IF "%DLURLD2%" == "" GOTO DLURLD2INT1 >NUL 2>&1
HTTPDL.exe -t 3 -T 3 -c -S%DELTASPIDER% -o CERTDLD2.txt %DLURLD2%/%HTTPDLFILE%
SET "HTTPDLERRORD2=%ERRORLEVEL%"
(IF "%WEBSPIDER%" == "0" (COPY "%HTTPDLFILE%" "CERTDLTMPD2\%HTTPDLFILE%" /Y)) >NUL 2>&1
(IF "%WEBSPIDER%" == "0" (IF EXIST "%HTTPDLFILE%" DEL "%HTTPDLFILE%")) >NUL 2>&1
(IF "%HTTPDLERRORD2%" == "4" SET "DLURLD2=") >NUL 2>&1
:DLURLD2INT1
IF "%DLURLD3%" == "" GOTO DLURLD3INT1 >NUL 2>&1
HTTPDL.exe -t 3 -T 3 -c -S%DELTASPIDER% -o CERTDLD3.txt %DLURLD3%/%HTTPDLFILE%
SET "HTTPDLERRORD3=%ERRORLEVEL%"
(IF "%WEBSPIDER%" == "0" (COPY "%HTTPDLFILE%" "CERTDLTMPD3\%HTTPDLFILE%" /Y)) >NUL 2>&1
(IF "%WEBSPIDER%" == "0" (IF EXIST "%HTTPDLFILE%" DEL "%HTTPDLFILE%")) >NUL 2>&1
(IF "%HTTPDLERRORD3%" == "4" SET "DLURLD3=") >NUL 2>&1
:DLURLD3INT1
IF "%DLURLD4%" == "" GOTO DLURLD4INT1 >NUL 2>&1
HTTPDL.exe -t 3 -T 3 -c -S%DELTASPIDER% -o CERTDLD4.txt %DLURLD4%/%HTTPDLFILE%
SET "HTTPDLERRORD4=%ERRORLEVEL%"
(IF "%WEBSPIDER%" == "0" (COPY "%HTTPDLFILE%" "CERTDLTMPD4\%HTTPDLFILE%" /Y)) >NUL 2>&1
(IF "%WEBSPIDER%" == "0" (IF EXIST "%HTTPDLFILE%" DEL "%HTTPDLFILE%")) >NUL 2>&1
(IF "%HTTPDLERRORD4%" == "4" SET "DLURLD4=") >NUL 2>&1
:DLURLD4INT1
IF "%DLURLD5%" == "" GOTO DLURLD5INT1 >NUL 2>&1
HTTPDL.exe -t 3 -T 3 -c -S%DELTASPIDER% -o CERTDLD5.txt %DLURLD5%/%HTTPDLFILE%
SET "HTTPDLERRORD5=%ERRORLEVEL%"
(IF "%WEBSPIDER%" == "0" (COPY "%HTTPDLFILE%" "CERTDLTMPD5\%HTTPDLFILE%" /Y)) >NUL 2>&1
(IF "%WEBSPIDER%" == "0" (IF EXIST "%HTTPDLFILE%" DEL "%HTTPDLFILE%")) >NUL 2>&1
(IF "%HTTPDLERRORD5%" == "4" SET "DLURLD5=") >NUL 2>&1
:DLURLD5INT1
TITLE=Roots and Revoked Certificates Updater

IF "%DLERROR%" == "1" GOTO LOOPDLINTJUMP1 >NUL 2>&1
((FOR /F "delims=  " %%f in (' TYPE "CERTDL.txt" ^|^ find /I "-Modified"') DO SET "MODDATE=%%f")&&(FOR /F "delims=.- " %%f in (' TYPE "CERTDL.txt" ^|^ find /I "failed"') DO SET "DLERROR=1")&&(FOR /F "delims=.- " %%f in (' TYPE "CERTDL.txt" ^|^ find /I "error"') DO SET "DLERROR=1")) >NUL 2>&1
IF "%MODDATE%" == "NA" (SET DLERROR=1) >NUL 2>&1
:LOOPDLINTJUMP1
IF "%DLURLD1%" == "" GOTO DLURLD1INT2 >NUL 2>&1
((FOR /F "delims=  " %%f in (' TYPE "CERTDLD1.txt" ^|^ find /I "-Modified"') DO SET "MODDATED1=%%f")&&(FOR /F "delims=.- " %%f in (' TYPE "CERTDLD1.txt" ^|^ find /I "failed"') DO SET "DLURLD1=")&&(FOR /F "delims=.- " %%f in (' TYPE "CERTDLD1.txt" ^|^ find /I "error"') DO SET "DLURLD1=")) >NUL 2>&1
IF "%MODDATED1%" == "NA" (SET DLURLD1=) >NUL 2>&1
:DLURLD1INT2
IF "%DLURLD2%" == "" GOTO DLURLD2INT2 >NUL 2>&1
((FOR /F "delims=  " %%f in (' TYPE "CERTDLD2.txt" ^|^ find /I "-Modified"') DO SET "MODDATED2=%%f")&&(FOR /F "delims=.- " %%f in (' TYPE "CERTDLD2.txt" ^|^ find /I "failed"') DO SET "DLURLD2=")&&(FOR /F "delims=.- " %%f in (' TYPE "CERTDLD2.txt" ^|^ find /I "error"') DO SET "DLURLD2=")) >NUL 2>&1
IF "%MODDATED2%" == "NA" (SET DLURLD2=) >NUL 2>&1
:DLURLD2INT2
IF "%DLURLD3%" == "" GOTO DLURLD3INT2 >NUL 2>&1
((FOR /F "delims=  " %%f in (' TYPE "CERTDLD3.txt" ^|^ find /I "-Modified"') DO SET "MODDATED3=%%f")&&(FOR /F "delims=.- " %%f in (' TYPE "CERTDLD3.txt" ^|^ find /I "failed"') DO SET "DLURLD3=")&&(FOR /F "delims=.- " %%f in (' TYPE "CERTDLD3.txt" ^|^ find /I "error"') DO SET "DLURLD3=")) >NUL 2>&1
IF "%MODDATED3%" == "NA" (SET DLURLD3=) >NUL 2>&1
:DLURLD3INT2
IF "%DLURLD4%" == "" GOTO DLURLD4INT2 >NUL 2>&1
((FOR /F "delims=  " %%f in (' TYPE "CERTDLD4.txt" ^|^ find /I "-Modified"') DO SET "MODDATED4=%%f")&&(FOR /F "delims=.- " %%f in (' TYPE "CERTDLD4.txt" ^|^ find /I "failed"') DO SET "DLURLD4=")&&(FOR /F "delims=.- " %%f in (' TYPE "CERTDLD4.txt" ^|^ find /I "error"') DO SET "DLURLD4=")) >NUL 2>&1
IF "%MODDATED4%" == "NA" (SET DLURLD4=) >NUL 2>&1
:DLURLD4INT2
IF "%DLURLD5%" == "" GOTO DLURLD5INT2 >NUL 2>&1
((FOR /F "delims=  " %%f in (' TYPE "CERTDLD5.txt" ^|^ find /I "-Modified"') DO SET "MODDATED5=%%f")&&(FOR /F "delims=.- " %%f in (' TYPE "CERTDLD5.txt" ^|^ find /I "failed"') DO SET "DLURLD5=")&&(FOR /F "delims=.- " %%f in (' TYPE "CERTDLD5.txt" ^|^ find /I "error"') DO SET "DLURLD5=")) >NUL 2>&1
IF "%MODDATED5%" == "NA" (SET DLURLD5=) >NUL 2>&1
:DLURLD5INT2

IF "%DLERROR%" == "1" GOTO LOOPDLINTJUMP2 >NUL 2>&1
(SET MODDATE1=%MODDATE:~22,2%&&SET MODDATE2=%MODDATE:~25,3%&&SET MODDATE3=%MODDATE:~29,4%) >NUL 2>&1
(IF "Jan" == "%MODDATE2%" SET MODDATE2=01) >NUL 2>&1
(IF "Feb" == "%MODDATE2%" SET MODDATE2=02) >NUL 2>&1
(IF "Mar" == "%MODDATE2%" SET MODDATE2=03) >NUL 2>&1
(IF "Apr" == "%MODDATE2%" SET MODDATE2=04) >NUL 2>&1
(IF "May" == "%MODDATE2%" SET MODDATE2=05) >NUL 2>&1
(IF "Jun" == "%MODDATE2%" SET MODDATE2=06) >NUL 2>&1
(IF "Jul" == "%MODDATE2%" SET MODDATE2=07) >NUL 2>&1
(IF "Aug" == "%MODDATE2%" SET MODDATE2=08) >NUL 2>&1
(IF "Sep" == "%MODDATE2%" SET MODDATE2=09) >NUL 2>&1
(IF "Oct" == "%MODDATE2%" SET MODDATE2=10) >NUL 2>&1
(IF "Nov" == "%MODDATE2%" SET MODDATE2=11) >NUL 2>&1
(IF "Dec" == "%MODDATE2%" SET MODDATE2=12) >NUL 2>&1
(SET MODCERTDATE=%MODDATE3%%MODDATE2%%MODDATE1%) >NUL 2>&1
:LOOPDLINTJUMP2
IF "%DLURLD1%" == "" GOTO DLURLD1INT3 >NUL 2>&1
(SET MODDATE1=%MODDATED1:~22,2%&&SET MODDATE2=%MODDATED1:~25,3%&&SET MODDATE3=%MODDATED1:~29,4%) >NUL 2>&1
(IF "Jan" == "%MODDATE2%" SET MODDATE2=01) >NUL 2>&1
(IF "Feb" == "%MODDATE2%" SET MODDATE2=02) >NUL 2>&1
(IF "Mar" == "%MODDATE2%" SET MODDATE2=03) >NUL 2>&1
(IF "Apr" == "%MODDATE2%" SET MODDATE2=04) >NUL 2>&1
(IF "May" == "%MODDATE2%" SET MODDATE2=05) >NUL 2>&1
(IF "Jun" == "%MODDATE2%" SET MODDATE2=06) >NUL 2>&1
(IF "Jul" == "%MODDATE2%" SET MODDATE2=07) >NUL 2>&1
(IF "Aug" == "%MODDATE2%" SET MODDATE2=08) >NUL 2>&1
(IF "Sep" == "%MODDATE2%" SET MODDATE2=09) >NUL 2>&1
(IF "Oct" == "%MODDATE2%" SET MODDATE2=10) >NUL 2>&1
(IF "Nov" == "%MODDATE2%" SET MODDATE2=11) >NUL 2>&1
(IF "Dec" == "%MODDATE2%" SET MODDATE2=12) >NUL 2>&1
(SET MODCERTDATED1=%MODDATE3%%MODDATE2%%MODDATE1%) >NUL 2>&1
:DLURLD1INT3
IF "%DLURLD2%" == "" GOTO DLURLD2INT3 >NUL 2>&1
(SET MODDATE1=%MODDATED2:~22,2%&&SET MODDATE2=%MODDATED2:~25,3%&&SET MODDATE3=%MODDATED2:~29,4%) >NUL 2>&1
(IF "Jan" == "%MODDATE2%" SET MODDATE2=01) >NUL 2>&1
(IF "Feb" == "%MODDATE2%" SET MODDATE2=02) >NUL 2>&1
(IF "Mar" == "%MODDATE2%" SET MODDATE2=03) >NUL 2>&1
(IF "Apr" == "%MODDATE2%" SET MODDATE2=04) >NUL 2>&1
(IF "May" == "%MODDATE2%" SET MODDATE2=05) >NUL 2>&1
(IF "Jun" == "%MODDATE2%" SET MODDATE2=06) >NUL 2>&1
(IF "Jul" == "%MODDATE2%" SET MODDATE2=07) >NUL 2>&1
(IF "Aug" == "%MODDATE2%" SET MODDATE2=08) >NUL 2>&1
(IF "Sep" == "%MODDATE2%" SET MODDATE2=09) >NUL 2>&1
(IF "Oct" == "%MODDATE2%" SET MODDATE2=10) >NUL 2>&1
(IF "Nov" == "%MODDATE2%" SET MODDATE2=11) >NUL 2>&1
(IF "Dec" == "%MODDATE2%" SET MODDATE2=12) >NUL 2>&1
(SET MODCERTDATED2=%MODDATE3%%MODDATE2%%MODDATE1%) >NUL 2>&1
:DLURLD2INT3
IF "%DLURLD3%" == "" GOTO DLURLD3INT3 >NUL 2>&1
(SET MODDATE1=%MODDATED3:~22,2%&&SET MODDATE2=%MODDATED3:~25,3%&&SET MODDATE3=%MODDATED3:~29,4%) >NUL 2>&1
(IF "Jan" == "%MODDATE2%" SET MODDATE2=01) >NUL 2>&1
(IF "Feb" == "%MODDATE2%" SET MODDATE2=02) >NUL 2>&1
(IF "Mar" == "%MODDATE2%" SET MODDATE2=03) >NUL 2>&1
(IF "Apr" == "%MODDATE2%" SET MODDATE2=04) >NUL 2>&1
(IF "May" == "%MODDATE2%" SET MODDATE2=05) >NUL 2>&1
(IF "Jun" == "%MODDATE2%" SET MODDATE2=06) >NUL 2>&1
(IF "Jul" == "%MODDATE2%" SET MODDATE2=07) >NUL 2>&1
(IF "Aug" == "%MODDATE2%" SET MODDATE2=08) >NUL 2>&1
(IF "Sep" == "%MODDATE2%" SET MODDATE2=09) >NUL 2>&1
(IF "Oct" == "%MODDATE2%" SET MODDATE2=10) >NUL 2>&1
(IF "Nov" == "%MODDATE2%" SET MODDATE2=11) >NUL 2>&1
(IF "Dec" == "%MODDATE2%" SET MODDATE2=12) >NUL 2>&1
(SET MODCERTDATED3=%MODDATE3%%MODDATE2%%MODDATE1%) >NUL 2>&1
:DLURLD3INT3
IF "%DLURLD4%" == "" GOTO DLURLD4INT3 >NUL 2>&1
(SET MODDATE1=%MODDATED4:~22,2%&&SET MODDATE2=%MODDATED4:~25,3%&&SET MODDATE3=%MODDATED4:~29,4%) >NUL 2>&1
(IF "Jan" == "%MODDATE2%" SET MODDATE2=01) >NUL 2>&1
(IF "Feb" == "%MODDATE2%" SET MODDATE2=02) >NUL 2>&1
(IF "Mar" == "%MODDATE2%" SET MODDATE2=03) >NUL 2>&1
(IF "Apr" == "%MODDATE2%" SET MODDATE2=04) >NUL 2>&1
(IF "May" == "%MODDATE2%" SET MODDATE2=05) >NUL 2>&1
(IF "Jun" == "%MODDATE2%" SET MODDATE2=06) >NUL 2>&1
(IF "Jul" == "%MODDATE2%" SET MODDATE2=07) >NUL 2>&1
(IF "Aug" == "%MODDATE2%" SET MODDATE2=08) >NUL 2>&1
(IF "Sep" == "%MODDATE2%" SET MODDATE2=09) >NUL 2>&1
(IF "Oct" == "%MODDATE2%" SET MODDATE2=10) >NUL 2>&1
(IF "Nov" == "%MODDATE2%" SET MODDATE2=11) >NUL 2>&1
(IF "Dec" == "%MODDATE2%" SET MODDATE2=12) >NUL 2>&1
(SET MODCERTDATED4=%MODDATE3%%MODDATE2%%MODDATE1%) >NUL 2>&1
:DLURLD4INT3
IF "%DLURLD5%" == "" GOTO DLURLD5INT3 >NUL 2>&1
(SET MODDATE1=%MODDATED5:~22,2%&&SET MODDATE2=%MODDATED5:~25,3%&&SET MODDATE3=%MODDATED5:~29,4%) >NUL 2>&1
(IF "Jan" == "%MODDATE2%" SET MODDATE2=01) >NUL 2>&1
(IF "Feb" == "%MODDATE2%" SET MODDATE2=02) >NUL 2>&1
(IF "Mar" == "%MODDATE2%" SET MODDATE2=03) >NUL 2>&1
(IF "Apr" == "%MODDATE2%" SET MODDATE2=04) >NUL 2>&1
(IF "May" == "%MODDATE2%" SET MODDATE2=05) >NUL 2>&1
(IF "Jun" == "%MODDATE2%" SET MODDATE2=06) >NUL 2>&1
(IF "Jul" == "%MODDATE2%" SET MODDATE2=07) >NUL 2>&1
(IF "Aug" == "%MODDATE2%" SET MODDATE2=08) >NUL 2>&1
(IF "Sep" == "%MODDATE2%" SET MODDATE2=09) >NUL 2>&1
(IF "Oct" == "%MODDATE2%" SET MODDATE2=10) >NUL 2>&1
(IF "Nov" == "%MODDATE2%" SET MODDATE2=11) >NUL 2>&1
(IF "Dec" == "%MODDATE2%" SET MODDATE2=12) >NUL 2>&1
(SET MODCERTDATED5=%MODDATE3%%MODDATE2%%MODDATE1%) >NUL 2>&1
:DLURLD5INT3

IF "%DLERROR%" == "0" (COPY "CERTDLTMP\%HTTPDLFILE%" "%HTTPDLFILE%" /Y) >NUL 2>&1

IF "%DLURLD1%" == "" GOTO DLURLD1INT4 >NUL 2>&1
IF "%WEBSPIDER%" == "0" GOTO DLURLD1INT4SP >NUL 2>&1
IF %MODCERTDATED1% LEQ %MODCERTDATE%  GOTO DLURLD1INT4 >NUL 2>&1
(IF EXIST "%HTTPDLFILE%" DEL "%HTTPDLFILE%") >NUL 2>&1
HTTPDL.exe -t 3 -T 3 -c -S -o CERTDLD1.txt %DLURLD1%/%HTTPDLFILE%
(COPY "%HTTPDLFILE%" "CERTDLTMPD1\%HTTPDLFILE%" /Y) >NUL 2>&1
(IF EXIST "%HTTPDLFILE%" DEL "%HTTPDLFILE%") >NUL 2>&1
(FOR /F "delims=  " %%f in (' TYPE "CERTDLD1.txt" ^|^ find /I "-Modified"') DO SET "MODDATED1=%%f") >NUL 2>&1
(SET MODDATE1=%MODDATED1:~22,2%&&SET MODDATE2=%MODDATED1:~25,3%&&SET MODDATE3=%MODDATED1:~29,4%) >NUL 2>&1
(IF "Jan" == "%MODDATE2%" SET MODDATE2=01) >NUL 2>&1
(IF "Feb" == "%MODDATE2%" SET MODDATE2=02) >NUL 2>&1
(IF "Mar" == "%MODDATE2%" SET MODDATE2=03) >NUL 2>&1
(IF "Apr" == "%MODDATE2%" SET MODDATE2=04) >NUL 2>&1
(IF "May" == "%MODDATE2%" SET MODDATE2=05) >NUL 2>&1
(IF "Jun" == "%MODDATE2%" SET MODDATE2=06) >NUL 2>&1
(IF "Jul" == "%MODDATE2%" SET MODDATE2=07) >NUL 2>&1
(IF "Aug" == "%MODDATE2%" SET MODDATE2=08) >NUL 2>&1
(IF "Sep" == "%MODDATE2%" SET MODDATE2=09) >NUL 2>&1
(IF "Oct" == "%MODDATE2%" SET MODDATE2=10) >NUL 2>&1
(IF "Nov" == "%MODDATE2%" SET MODDATE2=11) >NUL 2>&1
(IF "Dec" == "%MODDATE2%" SET MODDATE2=12) >NUL 2>&1
(SET MODCERTDATED1=%MODDATE3%%MODDATE2%%MODDATE1%) >NUL 2>&1
:DLURLD1INT4SP
(IF %MODCERTDATED1% GEQ %MODCERTDATE% (COPY "CERTDLTMPD1\%HTTPDLFILE%" "%HTTPDLFILE%" /Y)&&(SET "MODCERTDATE=%MODCERTDATED1%")) >NUL 2>&1
:DLURLD1INT4
IF "%DLURLD2%" == "" GOTO DLURLD2INT4 >NUL 2>&1
IF "%WEBSPIDER%" == "0" GOTO DLURLD2INT4SP >NUL 2>&1
IF %MODCERTDATED2% LEQ %MODCERTDATE%  GOTO DLURLD2INT4 >NUL 2>&1
(IF EXIST "%HTTPDLFILE%" DEL "%HTTPDLFILE%") >NUL 2>&1
HTTPDL.exe -t 3 -T 3 -c -S -o CERTDLD2.txt %DLURLD2%/%HTTPDLFILE%
(COPY "%HTTPDLFILE%" "CERTDLTMPD2\%HTTPDLFILE%" /Y) >NUL 2>&1
(IF EXIST "%HTTPDLFILE%" DEL "%HTTPDLFILE%") >NUL 2>&1
(FOR /F "delims=  " %%f in (' TYPE "CERTDLD2.txt" ^|^ find /I "-Modified"') DO SET "MODDATED2=%%f") >NUL 2>&1
(SET MODDATE1=%MODDATED2:~22,2%&&SET MODDATE2=%MODDATED2:~25,3%&&SET MODDATE3=%MODDATED2:~29,4%) >NUL 2>&1
(IF "Jan" == "%MODDATE2%" SET MODDATE2=01) >NUL 2>&1
(IF "Feb" == "%MODDATE2%" SET MODDATE2=02) >NUL 2>&1
(IF "Mar" == "%MODDATE2%" SET MODDATE2=03) >NUL 2>&1
(IF "Apr" == "%MODDATE2%" SET MODDATE2=04) >NUL 2>&1
(IF "May" == "%MODDATE2%" SET MODDATE2=05) >NUL 2>&1
(IF "Jun" == "%MODDATE2%" SET MODDATE2=06) >NUL 2>&1
(IF "Jul" == "%MODDATE2%" SET MODDATE2=07) >NUL 2>&1
(IF "Aug" == "%MODDATE2%" SET MODDATE2=08) >NUL 2>&1
(IF "Sep" == "%MODDATE2%" SET MODDATE2=09) >NUL 2>&1
(IF "Oct" == "%MODDATE2%" SET MODDATE2=10) >NUL 2>&1
(IF "Nov" == "%MODDATE2%" SET MODDATE2=11) >NUL 2>&1
(IF "Dec" == "%MODDATE2%" SET MODDATE2=12) >NUL 2>&1
(SET MODCERTDATED2=%MODDATE3%%MODDATE2%%MODDATE1%) >NUL 2>&1
:DLURLD2INT4SP
(IF %MODCERTDATED2% GEQ %MODCERTDATE% (COPY "CERTDLTMPD2\%HTTPDLFILE%" "%HTTPDLFILE%" /Y)&&(SET "MODCERTDATE=%MODCERTDATED2%")) >NUL 2>&1
:DLURLD2INT4
IF "%DLURLD3%" == "" GOTO DLURLD3INT4 >NUL 2>&1
IF "%WEBSPIDER%" == "0" GOTO DLURLD3INT4SP >NUL 2>&1
IF %MODCERTDATED3% LEQ %MODCERTDATE%  GOTO DLURLD3INT4 >NUL 2>&1
(IF EXIST "%HTTPDLFILE%" DEL "%HTTPDLFILE%") >NUL 2>&1
HTTPDL.exe -t 3 -T 3 -c -S -o CERTDLD3.txt %DLURLD3%/%HTTPDLFILE%
(COPY "%HTTPDLFILE%" "CERTDLTMPD3\%HTTPDLFILE%" /Y) >NUL 2>&1
(IF EXIST "%HTTPDLFILE%" DEL "%HTTPDLFILE%") >NUL 2>&1
(FOR /F "delims=  " %%f in (' TYPE "CERTDLD3.txt" ^|^ find /I "-Modified"') DO SET "MODDATED3=%%f") >NUL 2>&1
(SET MODDATE1=%MODDATED3:~22,2%&&SET MODDATE2=%MODDATED3:~25,3%&&SET MODDATE3=%MODDATED3:~29,4%) >NUL 2>&1
(IF "Jan" == "%MODDATE2%" SET MODDATE2=01) >NUL 2>&1
(IF "Feb" == "%MODDATE2%" SET MODDATE2=02) >NUL 2>&1
(IF "Mar" == "%MODDATE2%" SET MODDATE2=03) >NUL 2>&1
(IF "Apr" == "%MODDATE2%" SET MODDATE2=04) >NUL 2>&1
(IF "May" == "%MODDATE2%" SET MODDATE2=05) >NUL 2>&1
(IF "Jun" == "%MODDATE2%" SET MODDATE2=06) >NUL 2>&1
(IF "Jul" == "%MODDATE2%" SET MODDATE2=07) >NUL 2>&1
(IF "Aug" == "%MODDATE2%" SET MODDATE2=08) >NUL 2>&1
(IF "Sep" == "%MODDATE2%" SET MODDATE2=09) >NUL 2>&1
(IF "Oct" == "%MODDATE2%" SET MODDATE2=10) >NUL 2>&1
(IF "Nov" == "%MODDATE2%" SET MODDATE2=11) >NUL 2>&1
(IF "Dec" == "%MODDATE2%" SET MODDATE2=12) >NUL 2>&1
(SET MODCERTDATED3=%MODDATE3%%MODDATE2%%MODDATE1%) >NUL 2>&1
:DLURLD3INT4SP
(IF %MODCERTDATED3% GEQ %MODCERTDATE% (COPY "CERTDLTMPD3\%HTTPDLFILE%" "%HTTPDLFILE%" /Y)&&(SET "MODCERTDATE=%MODCERTDATED3%")) >NUL 2>&1
:DLURLD3INT4
IF "%DLURLD4%" == "" GOTO DLURLD4INT4 >NUL 2>&1
IF "%WEBSPIDER%" == "0" GOTO DLURLD4INT4SP >NUL 2>&1
IF %MODCERTDATED4% LEQ %MODCERTDATE%  GOTO DLURLD4INT4 >NUL 2>&1
(IF EXIST "%HTTPDLFILE%" DEL "%HTTPDLFILE%") >NUL 2>&1
HTTPDL.exe -t 3 -T 3 -c -S -o CERTDLD4.txt %DLURLD4%/%HTTPDLFILE%
(COPY "%HTTPDLFILE%" "CERTDLTMPD4\%HTTPDLFILE%" /Y) >NUL 2>&1
(IF EXIST "%HTTPDLFILE%" DEL "%HTTPDLFILE%") >NUL 2>&1
(FOR /F "delims=  " %%f in (' TYPE "CERTDLD4.txt" ^|^ find /I "-Modified"') DO SET "MODDATED4=%%f") >NUL 2>&1
(SET MODDATE1=%MODDATED4:~22,2%&&SET MODDATE2=%MODDATED4:~25,3%&&SET MODDATE3=%MODDATED4:~29,4%) >NUL 2>&1
(IF "Jan" == "%MODDATE2%" SET MODDATE2=01) >NUL 2>&1
(IF "Feb" == "%MODDATE2%" SET MODDATE2=02) >NUL 2>&1
(IF "Mar" == "%MODDATE2%" SET MODDATE2=03) >NUL 2>&1
(IF "Apr" == "%MODDATE2%" SET MODDATE2=04) >NUL 2>&1
(IF "May" == "%MODDATE2%" SET MODDATE2=05) >NUL 2>&1
(IF "Jun" == "%MODDATE2%" SET MODDATE2=06) >NUL 2>&1
(IF "Jul" == "%MODDATE2%" SET MODDATE2=07) >NUL 2>&1
(IF "Aug" == "%MODDATE2%" SET MODDATE2=08) >NUL 2>&1
(IF "Sep" == "%MODDATE2%" SET MODDATE2=09) >NUL 2>&1
(IF "Oct" == "%MODDATE2%" SET MODDATE2=10) >NUL 2>&1
(IF "Nov" == "%MODDATE2%" SET MODDATE2=11) >NUL 2>&1
(IF "Dec" == "%MODDATE2%" SET MODDATE2=12) >NUL 2>&1
(SET MODCERTDATED4=%MODDATE3%%MODDATE2%%MODDATE1%) >NUL 2>&1
:DLURLD4INT4SP
(IF %MODCERTDATED4% GEQ %MODCERTDATE% (COPY "CERTDLTMPD4\%HTTPDLFILE%" "%HTTPDLFILE%" /Y)&&(SET "MODCERTDATE=%MODCERTDATED4%")) >NUL 2>&1
:DLURLD4INT4
IF "%DLURLD5%" == "" GOTO DLURLD5INT4 >NUL 2>&1
IF "%WEBSPIDER%" == "0" GOTO DLURLD5INT4SP >NUL 2>&1
IF %MODCERTDATED5% LEQ %MODCERTDATE%  GOTO DLURLD5INT4 >NUL 2>&1
(IF EXIST "%HTTPDLFILE%" DEL "%HTTPDLFILE%") >NUL 2>&1
HTTPDL.exe -t 3 -T 3 -c -S -o CERTDLD5.txt %DLURLD5%/%HTTPDLFILE%
(COPY "%HTTPDLFILE%" "CERTDLTMPD5\%HTTPDLFILE%" /Y) >NUL 2>&1
(IF EXIST "%HTTPDLFILE%" DEL "%HTTPDLFILE%") >NUL 2>&1
(FOR /F "delims=  " %%f in (' TYPE "CERTDLD5.txt" ^|^ find /I "-Modified"') DO SET "MODDATED5=%%f") >NUL 2>&1
(SET MODDATE1=%MODDATED5:~22,2%&&SET MODDATE2=%MODDATED5:~25,3%&&SET MODDATE3=%MODDATED5:~29,4%) >NUL 2>&1
(IF "Jan" == "%MODDATE2%" SET MODDATE2=01) >NUL 2>&1
(IF "Feb" == "%MODDATE2%" SET MODDATE2=02) >NUL 2>&1
(IF "Mar" == "%MODDATE2%" SET MODDATE2=03) >NUL 2>&1
(IF "Apr" == "%MODDATE2%" SET MODDATE2=04) >NUL 2>&1
(IF "May" == "%MODDATE2%" SET MODDATE2=05) >NUL 2>&1
(IF "Jun" == "%MODDATE2%" SET MODDATE2=06) >NUL 2>&1
(IF "Jul" == "%MODDATE2%" SET MODDATE2=07) >NUL 2>&1
(IF "Aug" == "%MODDATE2%" SET MODDATE2=08) >NUL 2>&1
(IF "Sep" == "%MODDATE2%" SET MODDATE2=09) >NUL 2>&1
(IF "Oct" == "%MODDATE2%" SET MODDATE2=10) >NUL 2>&1
(IF "Nov" == "%MODDATE2%" SET MODDATE2=11) >NUL 2>&1
(IF "Dec" == "%MODDATE2%" SET MODDATE2=12) >NUL 2>&1
(SET MODCERTDATED5=%MODDATE3%%MODDATE2%%MODDATE1%) >NUL 2>&1
:DLURLD5INT4SP
(IF %MODCERTDATED5% GEQ %MODCERTDATE% (COPY "CERTDLTMPD5\%HTTPDLFILE%" "%HTTPDLFILE%" /Y)&&(SET "MODCERTDATE=%MODCERTDATED5%")) >NUL 2>&1
:DLURLD5INT4

IF "%DLERROR%" == "1" GOTO LOOPDLINTJUMP3 >NUL 2>&1
(IF "%DLFILENB%" == "1" SET "MODAUTHDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "2" SET "MODDELDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "3" SET "MODROOTDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "4" SET "MODUPDDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "5" SET "MODDISALLOWEDDATE=%MODCERTDATE%") >NUL 2>&1
:LOOPDLINTJUMP3
IF "%DLURLD1%" == "" GOTO DLURLD1INT5 >NUL 2>&1
(IF "%DLFILENB%" == "1" SET "MODAUTHDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "2" SET "MODDELDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "3" SET "MODROOTDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "4" SET "MODUPDDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "5" SET "MODDISALLOWEDDATE=%MODCERTDATE%") >NUL 2>&1
:DLURLD1INT5
IF "%DLURLD2%" == "" GOTO DLURLD2INT5 >NUL 2>&1
(IF "%DLFILENB%" == "1" SET "MODAUTHDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "2" SET "MODDELDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "3" SET "MODROOTDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "4" SET "MODUPDDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "5" SET "MODDISALLOWEDDATE=%MODCERTDATE%") >NUL 2>&1
:DLURLD2INT5
IF "%DLURLD3%" == "" GOTO DLURLD3INT5 >NUL 2>&1
(IF "%DLFILENB%" == "1" SET "MODAUTHDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "2" SET "MODDELDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "3" SET "MODROOTDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "4" SET "MODUPDDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "5" SET "MODDISALLOWEDDATE=%MODCERTDATE%") >NUL 2>&1
:DLURLD3INT5
IF "%DLURLD1%" == "" GOTO DLURLD4INT5 >NUL 2>&1
(IF "%DLFILENB%" == "1" SET "MODAUTHDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "2" SET "MODDELDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "3" SET "MODROOTDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "4" SET "MODUPDDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "5" SET "MODDISALLOWEDDATE=%MODCERTDATE%") >NUL 2>&1
:DLURLD4INT5
IF "%DLURLD5%" == "" GOTO DLURLD5INT5 >NUL 2>&1
(IF "%DLFILENB%" == "1" SET "MODAUTHDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "2" SET "MODDELDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "3" SET "MODROOTDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "4" SET "MODUPDDATE=%MODCERTDATE%") >NUL 2>&1
(IF "%DLFILENB%" == "5" SET "MODDISALLOWEDDATE=%MODCERTDATE%") >NUL 2>&1
:DLURLD5INT5

IF NOT %MODCERTDATE% GEQ %LASTCERTDATE% DEL "%HTTPDLFILE%" >NUL 2>&1

IF "%DLERROR%" == "1" GOTO LOOPDLINT >NUL 2>&1

IF "%ERRORLOOPS%" NEQ "0" GOTO ERRORLOOPSJUMP1 >NUL 2>&1
(IF NOT "%DLFILENB%" == "%DLFILES%" (SET /A DLFILENB=%DLFILENB%+1)) >NUL 2>&1
((SET /A LOOPDLFILES=%LOOPDLFILES%+1)&&(SET /A DLFILESINT=%DLFILES%+1)) >NUL 2>&1
IF "%LOOPDLFILES%" == "%DLFILESINT%" GOTO DLCERTEND >NUL 2>&1
GOTO LOOPDL >NUL 2>&1
:ERRORLOOPSJUMP1

IF NOT %MODCERTDATE% GEQ %LASTCERTDATE% GOTO DELTACERTDATEJUMP1 >NUL 2>&1
(IF NOT "%DLFILENB%" == "%DLFILES%" (SET /A DLFILENB=%DLFILENB%+1)) >NUL 2>&1
((SET /A LOOPDLFILES=%LOOPDLFILES%+1)&&(SET /A DLFILESINT=%DLFILES%+1)&&(SET LOOPCOUNTER=1)&&(SET WAITTIME=%SLEEPTIMER%)) >NUL 2>&1
IF "%LOOPDLFILES%" == "%DLFILESINT%" GOTO DLCERTEND >NUL 2>&1
GOTO LOOPDL >NUL 2>&1
:DELTACERTDATEJUMP1

CLS
ECHO.
ECHO  File %HTTPDLFILE% obsolete!
ECHO.
ECHO  Repeat download, please wait!
ECHO.
(SET /A WAITTIME=%WAITTIME%+1) >NUL 2>&1
ECHO  Try %LOOPCOUNTER% of %ERRORLOOPS% in %WAITTIME% seconds
ECHO.

:LOOPDLINT

IF "%ERRORLOOPS%" NEQ "0" GOTO ERRORLOOPSJUMP2 >NUL 2>&1
(IF NOT "%DLFILENB%" == "%DLFILES%" (SET /A DLFILENB=%DLFILENB%+1)) >NUL 2>&1
((SET /A LOOPDLFILES=%LOOPDLFILES%+1)&&(SET /A DLFILESINT=%DLFILES%+1)) >NUL 2>&1
IF "%LOOPDLFILES%" == "%DLFILESINT%" GOTO DLCERTEND >NUL 2>&1
GOTO LOOPDL >NUL 2>&1
:ERRORLOOPSJUMP2

IF "%DLERROR%" == "0" GOTO LOOPDLINTERROR >NUL 2>&1
CLS
ECHO.
ECHO  Network Error!
ECHO.
ECHO  Repeat download, please wait!
ECHO.
:LOOPDLINTERROR

IF "%LOOPDLFILES%" == "%DLFILESINT%" GOTO DLCERTEND >NUL 2>&1
IF NOT "%LOOPCOUNTER%" == "%ERRORLOOPS%" GOTO ERRORLOOPSJUMP3 >NUL 2>&1
(IF NOT "%DLFILENB%" == "%DLFILES%" (SET /A DLFILENB=%DLFILENB%+1)) >NUL 2>&1
((SET /A LOOPDLFILES=%LOOPDLFILES%+1)&&(SET /A DLFILESINT=%DLFILES%+1)&&(SET LOOPCOUNTER=0)&&(SET WAITTIME=%SLEEPTIMER%)) >NUL 2>&1
:ERRORLOOPSJUMP3

(SET /A LOOPCOUNTER=%LOOPCOUNTER%+1) >NUL 2>&1
(IF "%DLERROR%" == "0" (SLEEP %WAITTIME%)) >NUL 2>&1
GOTO LOOPDL >NUL 2>&1

:DLCERTEND

:NEXTINT3

Copy *.sst SST\ /Y >NUL 2>&1
(FOR /F "tokens=2* delims=	 " %%a IN ('REG QUERY "HKCU\Control Panel\International" /v "Locale"') DO SET LOCALETYPE=%%b) >NUL 2>&1
IF "%LOCALETYPE%"=="00000407" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000807" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000c07" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00001007" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00001407" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000809" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000082C" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000042C" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000042D" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000423" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000201A" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000141A" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000403" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000041A" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000101A" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000405" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000406" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000413" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00001809" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000425" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000438" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000040B" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000080C" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000C0C" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000040C" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000140C" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000180C" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000100C" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000462" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000042F" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000456" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000040E" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000040F" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000421" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000083C" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000410" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000810" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000043F" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000440" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000427" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000046E" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000083E" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000043E" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000043A" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000047A" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000450" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000414" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000814" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000415" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000416" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000816" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000086B" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000418" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000417" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000419" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000243B" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000103B" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000143B" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000C3B" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000043B" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000083B" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000203B" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000183B" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00001C3B" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000C1A" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00001C1A" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000081A" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000181A" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000041B" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000203B" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000340A" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000300A" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000C0A" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000041D" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000081D" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000444" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="0000041F" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000422" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000843" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000443" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000452" GOTO TF8 >NUL 2>&1
IF "%LOCALETYPE%"=="00000426" GOTO TF9 >NUL 2>&1
IF "%LOCALETYPE%"=="0000041C" GOTO TF11 >NUL 2>&1
IF "%LOCALETYPE%"=="00001409" GOTO TF13 >NUL 2>&1
IF "%LOCALETYPE%"=="00000481" GOTO TF13 >NUL 2>&1
IF "%LOCALETYPE%"=="0000046B" GOTO TF13 >NUL 2>&1
IF "%LOCALETYPE%"=="00000C6B" GOTO TF13 >NUL 2>&1
IF "%LOCALETYPE%"=="00002C0A" GOTO TF13 >NUL 2>&1
IF "%LOCALETYPE%"=="0000400A" GOTO TF13 >NUL 2>&1
IF "%LOCALETYPE%"=="0000240A" GOTO TF13 >NUL 2>&1
IF "%LOCALETYPE%"=="0000140A" GOTO TF13 >NUL 2>&1
IF "%LOCALETYPE%"=="00001C0A" GOTO TF13 >NUL 2>&1
IF "%LOCALETYPE%"=="0000440A" GOTO TF13 >NUL 2>&1
IF "%LOCALETYPE%"=="0000100A" GOTO TF13 >NUL 2>&1
IF "%LOCALETYPE%"=="0000480A" GOTO TF13 >NUL 2>&1
IF "%LOCALETYPE%"=="0000080A" GOTO TF13 >NUL 2>&1
IF "%LOCALETYPE%"=="00004C0A" GOTO TF13 >NUL 2>&1
IF "%LOCALETYPE%"=="0000180A" GOTO TF13 >NUL 2>&1
IF "%LOCALETYPE%"=="00003C0A" GOTO TF13 >NUL 2>&1
IF "%LOCALETYPE%"=="0000280A" GOTO TF13 >NUL 2>&1
IF "%LOCALETYPE%"=="0000500A" GOTO TF13 >NUL 2>&1
IF "%LOCALETYPE%"=="0000380A" GOTO TF13 >NUL 2>&1
IF "%LOCALETYPE%"=="0000200A" GOTO TF13 >NUL 2>&1

GOTO NEXTLOCALE1

:TF8
CLS
ECHO *******************************************************
FOR %%f in ("*root*.sst") DO ECHO * %%f		%%~tf  Roots       *
FOR %%f in ("*disallowed*.sst") DO ECHO * %%f	%%~tf  Revoked     *
ECHO *******************************************************
GOTO NEXTLOCALE2

:TF9
CLS
ECHO *******************************************************
FOR %%f in ("*root*.sst") DO ECHO * %%f		%%~tf  Roots      *
FOR %%f in ("*disallowed*.sst") DO ECHO * %%f	%%~tf  Revoked    *
ECHO *******************************************************
GOTO NEXTLOCALE2

:TF11
CLS
ECHO *******************************************************
FOR %%f in ("*root*.sst") DO ECHO * %%f		%%~tf Roots      *
FOR %%f in ("*disallowed*.sst") DO ECHO * %%f	%%~tf Revoked    *
ECHO *******************************************************
GOTO NEXTLOCALE2

:TF13
CLS
ECHO *******************************************************
FOR %%f in ("*root*.sst") DO ECHO * %%f		%%~tf Roots   *
FOR %%f in ("*disallowed*.sst") DO ECHO * %%f	%%~tf Revoked *
ECHO *******************************************************
GOTO NEXTLOCALE2

:NEXTLOCALE1
CLS
ECHO *******************************************************
FOR %%f in ("*root*.sst") DO ECHO * %%f		%%~tf Roots     *
FOR %%f in ("*disallowed*.sst") DO ECHO * %%f	%%~tf Revoked   *
ECHO *******************************************************
:NEXTLOCALE2

DEL *.sst /Q >NUL 2>&1
(FOR /F "tokens=1,2" %%c IN ('DATE /T') DO SET "INTDATEA=%%c"&&SET "INTDATEB=%%d") >NUL 2>&1
(FOR /F "tokens=1,2" %%c IN ('TIME /T') DO SET "INTTIMEA=%%c"&&SET "INTTIMEB=%%d") >NUL 2>&1
((SET "INTDATE=%INTDATEA% %INTDATEB%")&&(SET "INTTIME=%INTTIMEA% %INTTIMEB%")) >NUL 2>&1

IF NOT EXIST "SST\authroots.sst" GOTO NEXT1 >NUL 2>&1
IF NOT EXIST "SST\delroots.sst" GOTO NEXT1 >NUL 2>&1
IF NOT EXIST "SST\roots.sst" GOTO NEXT1 >NUL 2>&1
IF NOT EXIST "SST\updroots.sst" GOTO NEXT1 >NUL 2>&1
((REG ADD "HKLM\Software\Cert_Updater" /f /v "%DLDATEREGNAME1%%DATEREGNAMEEND%" /t REG_SZ /d %MODAUTHDATE%)&&(REG ADD "HKLM\Software\Cert_Updater" /f /v "%DLDATEREGNAME2%%DATEREGNAMEEND%" /t REG_SZ /d %MODDELDATE%)&&(REG ADD "HKLM\Software\Cert_Updater" /f /v "%DLDATEREGNAME3%%DATEREGNAMEEND%" /t REG_SZ /d %MODROOTDATE%)&&(REG ADD "HKLM\Software\Cert_Updater" /f /v "%DLDATEREGNAME4%%DATEREGNAMEEND%" /t REG_SZ /d %MODUPDDATE%)) >NUL 2>&1
CD SST
Rundll32.exe advpack.dll,LaunchINFSection rootsupd.inf,DefaultInstall
ECHO *******************************************************
ECHO *                                                     *
ECHO *                 Roots  Certificates                 *
ECHO *                                                     *
ECHO *                successfully updated!                *
ECHO *                                                     *
ECHO *******************************************************
CD..
(REG ADD "HKLM\Software\Cert_Updater" /f /v "Last Update Roots" /t REG_SZ /d "%INTDATE%  %INTTIME%  Status OK") >NUL 2>&1
(IF "%LogFileEnable%" == "1" ECHO %INTDATE%  %INTTIME%     Roots Certificates successfully updated! >> "%windir%\Cert_Updater.log") >NUL 2>&1
GOTO NEXT2
:NEXT1
ECHO *******************************************************
ECHO *                                                     *
ECHO *                 Roots  Certificates                 *
ECHO *                                                     *
ECHO *                could not be updated!                *
ECHO *                                                     *
ECHO *******************************************************
(REG ADD "HKLM\Software\Cert_Updater" /f /v "Last Update Roots" /t REG_SZ /d "%INTDATE%  %INTTIME%  Status Error") >NUL 2>&1
(IF "%LogFileEnable%" == "1" ECHO %INTDATE%  %INTTIME%     Roots Certificates could not be updated! >> "%windir%\Cert_Updater.log") >NUL 2>&1
:NEXT2
IF NOT EXIST "SST\disallowedcert.sst" GOTO NEXT3 >NUL 2>&1
(REG ADD "HKLM\Software\Cert_Updater" /f /v "%DLDATEREGNAME5%%DATEREGNAMEEND%" /t REG_SZ /d %MODDISALLOWEDDATE%) >NUL 2>&1
CD SST
Rundll32.exe advpack.dll,LaunchINFSection rvkroots.inf,DefaultInstall
ECHO *******************************************************
ECHO *                                                     *
ECHO *                Revoked  Certificates                *
ECHO *                                                     *
ECHO *                successfully updated!                *
ECHO *                                                     *
ECHO *******************************************************
CD..
(REG ADD "HKLM\Software\Cert_Updater" /f /v "Last Update Revoked" /t REG_SZ /d "%INTDATE%  %INTTIME%  Status Ok") >NUL 2>&1
(IF "%LogFileEnable%" == "1" ECHO %INTDATE%  %INTTIME%     Revoked Certificates successfully updated! >> "%windir%\Cert_Updater.log") >NUL 2>&1
GOTO NEXT4
:NEXT3
ECHO *******************************************************
ECHO *                                                     *
ECHO *                Revoked  Certificates                *
ECHO *                                                     *
ECHO *                could not be updated!                *
ECHO *                                                     *
ECHO *******************************************************
(REG ADD "HKLM\Software\Cert_Updater" /f /v "Last Update Revoked" /t REG_SZ /d "%INTDATE%  %INTTIME%  Status Error") >NUL 2>&1
(IF "%LogFileEnable%" == "1" ECHO %INTDATE%  %INTTIME%     Revoked Certificates could not be updated! >> "%windir%\Cert_Updater.log") >NUL 2>&1
:NEXT4
(IF "%LogFileEnable%" == "1" ECHO. >> "%windir%\Cert_Updater.log") >NUL 2>&1
IF "%EndTimer%" == "0" (PAUSE) ELSE (sleep.exe %EndTimer%)
